# Generated by Django 6.0.5 on 2026-05-30 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('app_id', models.AutoField(primary_key=True, serialize=False)),
                ('app_name', models.CharField(max_length=100)),
                ('app_type', models.CharField(blank=True, max_length=50)),
                ('ip_address', models.CharField(blank=True, max_length=50)),
                ('hostname', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'apps',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('action_type', models.CharField(blank=True, max_length=100)),
                ('entity_name', models.CharField(blank=True, max_length=100)),
                ('entity_id', models.IntegerField(blank=True, null=True)),
                ('action_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'audit_logs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('evidence_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_path', models.CharField(max_length=255)),
                ('collected_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'evidence',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('incident_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('detection_date', models.DateTimeField(auto_now_add=True)),
                ('lessons_learned', models.TextField(blank=True)),
                ('resolved_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'incidents',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IncidentAsset',
            fields=[
                ('incident_asset_id', models.AutoField(primary_key=True, serialize=False)),
                ('impact_type', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'incident_assets',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IncidentCategory',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'incident_categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IncidentIoc',
            fields=[
                ('incident_ioc_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'incident_iocs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IncidentPlaybook',
            fields=[
                ('incident_playbook_id', models.AutoField(primary_key=True, serialize=False)),
                ('steps_followed', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'incident_playbooks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IncidentStatus',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'incident_status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IncidentUpdate',
            fields=[
                ('update_id', models.AutoField(primary_key=True, serialize=False)),
                ('update_message', models.TextField()),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'incident_updates',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ioc',
            fields=[
                ('ioc_id', models.AutoField(primary_key=True, serialize=False)),
                ('ioc_type', models.CharField(max_length=50)),
                ('ioc_value', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'iocs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MetricsLog',
            fields=[
                ('metric_id', models.AutoField(primary_key=True, serialize=False)),
                ('metric_type', models.CharField(max_length=100)),
                ('value_numeric', models.DecimalField(decimal_places=2, max_digits=10)),
                ('measured_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'metrics_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Playbook',
            fields=[
                ('playbook_id', models.AutoField(primary_key=True, serialize=False)),
                ('playbook_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'playbooks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlaybookStep',
            fields=[
                ('step_id', models.AutoField(primary_key=True, serialize=False)),
                ('step_number', models.IntegerField()),
                ('step_description', models.TextField()),
            ],
            options={
                'db_table': 'playbook_steps',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('priority_id', models.AutoField(primary_key=True, serialize=False)),
                ('priority_level', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'priorities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ResponseAction',
            fields=[
                ('action_id', models.AutoField(primary_key=True, serialize=False)),
                ('action_type', models.CharField(max_length=100)),
                ('was_successful', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'response_actions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.AutoField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=100, unique=True)),
                ('specialization', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'teams',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ThreatFeed',
            fields=[
                ('feed_id', models.AutoField(primary_key=True, serialize=False)),
                ('feed_name', models.CharField(max_length=100)),
                ('source_url', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'threat_feeds',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('channel_id', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
